---
- name: Deploy Docker Image to Container
  hosts: all

  tasks:
    - name: Pull Docker Image
      docker_image:
        name: vishalsin25/miniproject
        tag: latest
        source: pull

    - name: Create & Start Calculator Docker Container
      docker_container:
        name: Calculator_SPE_mini
        image: vishalsin25/miniproject
        state: started
        tty: yes
        interactive: yes